kibalabs/ui-react

ui-react/src/welcome.stories.mdx

Fix - documentation typo

---

CHANGELOG.md
ui-react/src/atoms/index.ts
ui-react/src/atoms/progressCounterItem/buildTheme.ts
ui-react/src/atoms/progressCounterItem/component.tsx
ui-react/src/atoms/tabBarItem/buildTheme.ts
ui-react/src/atoms/tabBarItem/component.tsx
ui-react/src/atoms/tabBarItem/documentation.stories.mdx
ui-react/src/atoms/tabBarItem/index.ts
ui-react/src/atoms/tabBarItem/theme.ts
ui-react/src/molecules/index.ts
ui-react/src/molecules/tabBar/component.tsx
ui-react/src/molecules/tabBar/documentation.stories.mdx
ui-react/src/molecules/tabBar/index.ts
ui-react/src/theming/theme.ts
ui-react/src/theming/themeBuilder.tsx

New TabBar component (with TabBarItem atom for theming).
As usual, intended to be re-usable but first use is for everypage console tabs
Storybook:
Working in everypage locally:

Feature - Create TabBar (& TabBarItem) component

---

ui-react/src/atoms/link/buildTheme.ts
ui-react/src/atoms/webView/component.tsx
ui-react/src/layouts/stack/component.tsx
ui-react/src/subatoms/box/component.tsx
ui-react/src/subatoms/colors/buildTheme.ts
ui-react/src/subatoms/text/buildTheme.ts
ui-react/src/wrappers/paddingView/component.tsx
ui-react/src/wrappers/responsiveTextAlignmentView/component.tsx

All changes made whilst updating everysize (https://everysize-app.kibalabs.com) to use ui-react directly 🎉

Feature - Add themes for text + Small fixes for a number of components

---

CHANGELOG.md
src/atoms/linkBase/buildTheme.ts
src/atoms/linkBase/documentation.stories.mdx
src/layouts/container/component.tsx
src/particles/text/buildTheme.ts

Feature - add card variant to linkBase

---

.github/workflows/deploy.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
CHANGELOG.md
src/atoms/index.ts

Fix - add pill to atom exports

---

package.json

Fix - remove directory from repository in package.json

---

.storybook/main.js
package-lock.json
package.json
src/atoms/button/component.tsx
src/atoms/iconButton/component.tsx
src/atoms/linkBase/component.tsx
src/atoms/webView/component.tsx

Feature - update dependencies

---

CHANGELOG.md
src/atoms/webView/component.tsx
src/atoms/webView/documentation.stories.mdx

Feature - update WebView to be lazyloadable + add aspectRatio prop to WebView

---

.storybook/main.js
CHANGELOG.md
package-lock.json
package.json
src/layouts/stack/component.tsx
src/layouts/stack/documentation.stories.mdx
src/molecules/carousel/component.tsx
src/organisms/documentation.stories.mdx
src/organisms/markdown.tsx
src/organisms/markdownText.tsx
src/theming/themeContext.tsx
src/wrappers/wrappingComponent.tsx

Fix - small errors caused by typing PR

---

CHANGELOG.md
src/wrappers/backgroundView/component.tsx

Fix - update BackgroundView to not reverse order of layers in place

---

CHANGELOG.md
package-lock.json
package.json
src/atoms/bulletText/component.tsx
src/atoms/button/component.tsx
src/atoms/iconButton/component.tsx
src/atoms/linePager/component.tsx
src/atoms/linkBase/component.tsx
src/atoms/webView/component.tsx
src/layouts/equalGrid/component.tsx
src/layouts/grid/component.tsx
src/layouts/stack/component.tsx
src/molecules/carousel/component.tsx
src/molecules/tabBar/component.tsx
src/organisms/markdown.tsx
src/organisms/markdownText.tsx
src/particles/dimensions/theme.ts
src/particles/image/component.tsx
src/particles/media/component.tsx
src/particles/video/component.tsx
src/theming/themeContext.tsx
src/wrappers/paddingView/component.tsx
src/wrappers/responsiveContainingView/component.tsx

Lots of typing fixes that came about in https://github.com/kibalabs/everypage/pull/4/files

Feature - update typing based on use in everypage

---

CHANGELOG.md
src/atoms/index.ts
src/atoms/titledCollapsibleBox/componentStateful.tsx
src/atoms/titledCollapsibleBox/documentation.stories.mdx
src/atoms/titledCollapsibleBox/index.ts

Feature - Created StatefulTitledCollapsibleBox atom

---

CHANGELOG.md
src/organisms/documentation.stories.mdx
src/organisms/markdown.tsx
src/organisms/markdownText.tsx
src/util/componentUtil.ts
src/util/index.ts

Fix - Update Markdown component to use unmargined text when emebedded in other text

---

CHANGELOG.md
src/atoms/tabBarItem/component.tsx
src/molecules/markdown/component.tsx
src/molecules/markdownText/component.tsx

Feature - Memoize Markdown and MarkdownText to prevent expensive re-renders

---

CHANGELOG.md
src/atoms/button/buildTheme.ts
src/atoms/checkbox/buildTheme.ts
src/atoms/inputWrapper/buildTheme.ts
src/atoms/link/buildTheme.ts
src/molecules/markdownText/component.tsx
src/particles/text/buildTheme.ts

Feature - small updates to default theming

---

CHANGELOG.md
src/atoms/inputWrapper/component.tsx
src/model/inputType.ts
src/molecules/index.ts
src/molecules/multiLineInput/component.tsx
src/molecules/multiLineInput/documentation.stories.mdx
src/molecules/multiLineInput/index.ts
src/molecules/singleLineInput/component.tsx
src/molecules/singleLineInput/documentation.stories.mdx

MultiLineInput component added
Input Types updated to have number and tel for input fields

Feature - created MultiLineInput molecule

---

src/molecules/multiLineInput/component.tsx
src/molecules/multiLineInput/documentation.stories.mdx
src/molecules/singleLineInput/component.tsx
src/molecules/singleLineInput/documentation.stories.mdx

- [.] I have updated the CHANGELOG with a summary of my changes
- [.] I have updated the documentation accordingly

Fix - clean up quirks in MultiLineInput

---

src/atoms/bulletText/documentation.stories.mdx
src/atoms/checkbox/documentation.stories.mdx
src/molecules/form/documentation.stories.mdx
src/molecules/singleLineInput/documentation.stories.mdx

There is a problem in BulletText documentation. I have attached the screenshot of this problem.

Feature - Added stateful examples to SingleLineInput, Checkbox and Form docs

---

src/wrappers/responsiveContainingView/component.tsx

Feature - Responsive containing view updated to center horizontally

---

CHANGELOG.md
src/app/kibaApp.tsx

Feature - add size to KibaApp to fix wierd bug

---

package-lock.json
package.json

Feature - update dependencies to latest version

---

src/molecules/list/component.tsx

Fix - remove requirement for lists to always have children

---

src/molecules/multiLineInput/component.tsx

Fix - MultiLineInput to resize correctly when minLineCount is higher than maxLineCount

---

CHANGELOG.md
package-lock.json
src/layouts/stack/component.tsx

Fix - correct scrolling class usage in Stack

---

CHANGELOG.md
src/molecules/list/component.tsx
src/molecules/list/documentation.stories.mdx
src/particles/divider/buildTheme.ts
src/particles/divider/component.tsx
src/particles/divider/documentation.stories.mdx
src/particles/divider/index.ts
src/particles/divider/theme.ts
src/particles/index.ts
src/theming/theme.ts
src/theming/themeBuilder.tsx

The divider is not styled properly. I am not able to get the perfect look for it.

Feature - Created Divider particle + Add dividers to Lists

---

package-lock.json
src/atoms/button/documentation.stories.mdx
src/atoms/button/index.ts
src/atoms/button/themeExample.tsx
src/atoms/tabBarItem/component.tsx
src/molecules/tabBar/component.tsx

Feature - Atom theming prototype

---

CHANGELOG.md
src/particles/box/component.tsx
src/particles/box/documentation.stories.mdx

Feature- Box props updated to have child optional

---

CHANGELOG.md
src/layouts/stack/component.tsx
src/layouts/stack/documentation.stories.mdx

Feature - Flex Wrap added to Stack

---

CHANGELOG.md
src/particles/box/component.tsx
src/particles/box/documentation.stories.mdx

Feature - tooltip added to Box

---

CHANGELOG.md
src/layouts/equalGrid/component.tsx
src/layouts/grid/component.tsx
src/layouts/grid/documentation.stories.mdx

Feature - Added defaultGutter prop to Grid and EqualGrid

---

CHANGELOG.md
src/atoms/linkBase/component.tsx

Feature - isFullHeight prop added to LinkBase

---

src/hooks/index.ts
src/hooks/useResponsiveScreenSize.ts
src/index.ts
src/molecules/carousel/component.tsx
src/particles/dimensions/theme.ts
src/theming/index.ts
src/util/index.ts

Fix - move useResponsiveScreenSize to its own folder to prevent import cycles

---

src/layouts/grid/component.tsx
src/layouts/grid/documentation.stories.mdx
src/util/index.ts

Fix - update Grid to use 0px as empty gutter

---

CHANGELOG.md
src/molecules/tabBar/component.tsx
src/molecules/tabBar/documentation.stories.mdx
src/util/index.ts

Feature - Added contentAlignment prop to TabBar

---

src/atoms/pill/component.tsx

Fix - update Pill component icon prop types

---

CHANGELOG.md
src/app/globalCss.tsx
src/app/kibaApp.tsx
src/atoms/inputWrapper/component.tsx
src/atoms/webView/documentation.stories.mdx
src/layouts/grid/component.tsx
src/layouts/stack/component.tsx
src/layouts/stack/documentation.stories.mdx
src/molecules/carousel/component.tsx
src/molecules/form/component.tsx
src/molecules/inputFrame/component.tsx
src/molecules/markdown/component.tsx
src/molecules/markdownText/component.tsx
src/molecules/progressCounter/component.tsx
src/particles/image/component.tsx
src/particles/video/component.tsx
src/theming/themeBuilder.tsx
src/wrappers/backgroundView/component.tsx

Feature - Updated Stack to have vertical gutter between wrapped stack items

---

.storybook/preview.js
CHANGELOG.md
src/atoms/pill/buildTheme.ts
src/particles/box/buildTheme.ts
src/particles/box/component.tsx
src/particles/box/documentation.stories.mdx

Feature - Updated Box to have shouldClipContent prop

---

CHANGELOG.md
src/particles/text/component.tsx
src/particles/text/documentation.stories.mdx

We should also give a warning in case where someone is using IE11, so that user knows that only single line truncation is possible in IE11.

Feature - Added `lineLimit` prop to Text component

---

CHANGELOG.md
src/atoms/button/component.tsx
src/atoms/iconButton/component.tsx
src/atoms/link/component.tsx
src/atoms/linkBase/component.tsx

Feature - Updated Button, Link, LinkBase component to have TabIndex Prop

---

src/molecules/optionSelect/component.tsx

Feature - export IOption from OptionSelect

---

CHANGELOG.md
src/app/globalCss.tsx

Adds more browser support (specifically Edge)

Feature - moved colors css to root 

---

CHANGELOG.md
src/particles/media/component.tsx

Featre: Update Media to process urls more accurately

---

src/particles/media/component.tsx

Fix: ignore empty urls in Media 

---

CHANGELOG.md
package-lock.json
package.json
src/atoms/titledCollapsibleBox/component.tsx

Feature: update TitledCollapsibleBox to clip children so borders look nice

---

CHANGELOG.md
src/atoms/titledCollapsibleBox/component.tsx

Fix: TitledCollapsibleBox to only collapse when clicking on the title area

---

.github/workflows/deploy.yml
package-lock.json
package.json
src/molecules/markdown/component.tsx
src/molecules/markdownText/component.tsx

Feature: add deployment of "next" docs + update dependencies

---

.github/workflows/deploy.yml
.github/workflows/release.yml
docs.Dockerfile

Fix: Update docs docker build to use correct file

---

src/particles/media/component.tsx
src/particles/media/documentation.stories.mdx

Currently, the media component checks for URL extension to determine if it is a video or an image.
This change will Check the content type of URL without extension and determine if it's a video, image and uses an Iframe if it cannot determine the type.

Feature: Update media component to check Content-Type of links without extension

---

CHANGELOG.md
src/atoms/link/component.tsx

Feature: update Link to not have a default for shouldOpenSameTab

---

src/atoms/button/component.tsx
src/atoms/iconButton/component.tsx
src/atoms/link/component.tsx
src/atoms/linkBase/component.tsx

Fix: Only use CoreLink for same tab navigation in Buttons and Links

---

.storybook/main.js
package-lock.json
package.json
src/app/headContext.tsx
src/particles/media/component.tsx

Fix: Small updates to Head for SSR

---

CHANGELOG.md
src/app/kibaApp.tsx

Feature: add background to KibaApp

---

CHANGELOG.md
src/atoms/button/component.tsx
src/atoms/iconButton/component.tsx
src/atoms/link/component.tsx
src/atoms/linkBase/component.tsx
src/atoms/webView/component.tsx

Fix: update buttons and links to only use CoreLink for internal links

---

CHANGELOG.md
src/app/headContext.tsx

Feature: expose renderHead

---

.github/workflows/deploy.yml
.github/workflows/release.yml
src/molecules/carousel/component.tsx
src/particles/portal/component.tsx

Fiddle: update deployment to use specific ports

---

CHANGELOG.md
src/atoms/listItem/component.tsx
src/atoms/listItem/documentation.stories.mdx
src/molecules/list/documentation.stories.mdx

Fix: update list Item so it's not clickable when disabled

---

CHANGELOG.md
src/layouts/layerContainer/component.tsx
src/layouts/layerContainer/documentation.stories.mdx
src/molecules/form/component.tsx
src/molecules/form/documentation.stories.mdx

Feature: Add isStatic to LayerContainer.Layer to allow self-sizing + Update Form to use LayerContainer

---

CHANGELOG.md
src/atoms/link/component.tsx
src/atoms/link/documentation.stories.mdx

KIBA-1343: add onclicked to link

---

CHANGELOG.md
src/atoms/button/component.tsx
src/atoms/iconButton/component.tsx
src/atoms/link/component.tsx
src/atoms/linkBase/component.tsx

Fix: Update Link, LinkBase, IconButton and Button to not use CoreLink for fragments

---

CHANGELOG.md
src/atoms/button/component.tsx
src/atoms/button/documentation.stories.mdx

Fiddle: wrap button text in a span

---

package-lock.json
package.json
src/atoms/button/buildTheme.ts
src/atoms/button/documentation.stories.mdx

Fix: make button text default center aligned

---

CHANGELOG.md
src/particles/video/component.tsx
src/particles/video/documentation.stories.mdx

Feature: add event callbakcs to Video

---

package-lock.json
package.json
src/molecules/markdownText/component.tsx
src/molecules/markdownText/documentation.stories.mdx

Fix: undo breaking change to MarkdownText spacing

---

src/molecules/markdownText/component.tsx
src/molecules/markdownText/documentation.stories.mdx

Fix: force MarkdownText to be unmargined

---

package-lock.json
package.json
src/molecules/list/component.tsx
src/molecules/tabBar/component.tsx

Fiddle: update dependencies

---

CHANGELOG.md
src/atoms/button/component.tsx
src/atoms/iconButton/component.tsx

Fix: use buttonType correctly in Button and IconButton 

---

CHANGELOG.md
src/layouts/stack/component.tsx

Feature: Updated Stack to inherit min-height when isFullHeight is true

---

CHANGELOG.md
src/atoms/dialog/component.tsx

Fix: make Dialog ssr safe

---

CHANGELOG.md
src/layouts/equalGrid/component.tsx

Fiddle: add padding props to EqualGrid

---

CHANGELOG.md
src/particles/box/component.tsx

Feature: added minHeight and minWidth to Box

---

CHANGELOG.md
src/particles/media/component.tsx

Fix: Update Media to follow redirects when fetching for content-type

---

.github/workflows/deploy.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
src/app/globalCss.tsx

Fix: update Links to be excluded from global styles

---

CHANGELOG.md
src/atoms/link/buildTheme.ts

Feature: Make links inherit style by default

---

CHANGELOG.md
src/atoms/dialog/component.tsx
src/molecules/optionSelect/component.tsx
src/particles/colors/buildTheme.ts
src/wrappers/colorSettingView/component.tsx

Fix: correct alternateColors calculation + add placeholderText to OptionSelect

---

CHANGELOG.md
src/molecules/optionSelect/component.tsx

Fix: Use optionTextVariant correctly in OptionSelect

---

CHANGELOG.md
src/particles/text/component.tsx

Feature: add shouldBreakOnWords and shouldBreakAnywhere to Text

---

CHANGELOG.md
src/particles/image/component.tsx
src/particles/image/documentation.stories.mdx

KIBA-1532: Update Image to work with responsive images

---

CHANGELOG.md
src/atoms/titledCollapsibleBox/componentStateful.tsx

Fix: Update StatefulTitleCollapsibleBox to pass through className

---

CHANGELOG.md
src/atoms/button/component.tsx
src/atoms/iconButton/component.tsx
src/atoms/link/component.tsx
src/atoms/linkBase/component.tsx

Fiddle: Updated Button, IconButton, LinkBase and Link to stop propagating events

---

src/app/kibaApp.tsx
src/particles/image/component.tsx

Fix: set min lazy image size to 1px

---

src/layouts/layerContainer/component.tsx

Fiddle: update LayerContainer with improved End alignment

---

CHANGELOG.md
src/atoms/button/component.tsx

Feature: add props to Button to allow more layouts

---

CHANGELOG.md
src/particles/box/component.tsx

Feature: add responsive size props to Box

---

CHANGELOG.md
src/atoms/button/component.tsx
src/particles/box/buildTheme.ts
src/particles/box/theme.ts

Fix: use correct disabled style on button + Add opacity to Box

---

CHANGELOG.md
package-lock.json
package.json
src/molecules/markdown/component.tsx
src/particles/image/documentation.stories.mdx
src/particles/media/component.tsx
src/particles/media/documentation.stories.mdx
src/particles/video/component.tsx
src/wrappers/wrappingComponent.tsx

Fiddle: update markdown dependency

---

CHANGELOG.md

Fiddle: clean up changelog

---

.github/workflows/pull-request.yml
CHANGELOG.md
src/molecules/form/component.tsx

Feature: added postTarget as alternative to onFormSubmitted for Form

---

src/layouts/stack/component.tsx
src/particles/box/component.tsx

Fiddle: update stack and box sizing props to have empty defaults

---

CHANGELOG.md
src/layouts/grid/component.tsx

Fiddle: update Grid.Item to use flex display

---

CHANGELOG.md
src/atoms/checkbox/component.tsx
src/atoms/titledCollapsibleBox/component.tsx
src/atoms/titledCollapsibleBox/componentStateful.tsx
src/particles/icon/component.tsx

Fiddle: update Checkbox and TitledCollapsibleBox for performance

---

src/particles/icon/component.tsx

Fix: undo bad changes to Icon

---

CHANGELOG.md
src/atoms/selectableView/buildTheme.ts
src/atoms/selectableView/component.tsx
src/atoms/selectableView/index.ts
src/atoms/selectableView/theme.ts
src/theming/theme.ts
src/theming/themeBuilder.tsx

Feature: Added SelectableView atom

---

CHANGELOG.md
src/particles/image/component.tsx
src/particles/media/component.tsx
src/particles/video/component.tsx

Feature: enabled IPFS source in Image and Video

---

src/atoms/iconButton/buildTheme.ts
src/atoms/linePager/buildTheme.ts

Fiddle: update tertiary themes

---

CHANGELOG.md
src/atoms/dialog/component.tsx

Fiddle: Added shouldSkipRenderingWhenClosed to Dialog

---

CHANGELOG.md
package-lock.json
package.json
src/molecules/singleLineInput/component.tsx

Feature: Added shouldHideNumberSpinButtons and shouldStopNumberScrolling to SingleLineInput

---

CHANGELOG.md
src/molecules/markdownText/component.tsx

Fix: Update MarkdownText to render newlines more intuitively

---

CHANGELOG.md
src/atoms/button/component.tsx
src/atoms/inputWrapper/buildTheme.ts
src/particles/text/component.tsx
src/util/responsiveUtil.ts

Fiddle: Added alignmentResponsive to Text

---

CHANGELOG.md
src/molecules/markdown/component.tsx

Feature: Added extraOverrideComponents to Markdown

---

CHANGELOG.md
src/molecules/markdown/component.tsx
src/particles/media/component.tsx

Fiddle: Added more known extensions to Media

---

.github/workflows/deploy-beta.yml
.github/workflows/deploy.yml
.github/workflows/release.yml

Fiddle: update deployment

---

CHANGELOG.md
src/app/kibaApp.tsx
src/molecules/appDownloadButton/component.tsx
src/molecules/optionSelect/component.tsx
src/particles/fonts/buildTheme.ts
src/particles/kibaIcon/component.tsx

Fiddle: update assets cdn url

---

CHANGELOG.md
src/app/globalCss.tsx
src/atoms/bulletList/component.tsx
src/atoms/bulletText/buildTheme.ts
src/atoms/bulletText/component.tsx

Fiddle: improve alignment for BulletList and BulletText

---

package-lock.json
package.json
src/app/kibaApp.tsx
src/layouts/grid/component.tsx
src/layouts/layerContainer/component.tsx
src/molecules/progressCounter/component.tsx
src/molecules/tabBar/component.tsx
src/wrappers/backgroundView/component.tsx
src/wrappers/colorSettingView/component.tsx
src/wrappers/containingView/component.tsx
src/wrappers/hidingView/component.tsx
src/wrappers/paddingView/component.tsx
src/wrappers/responsiveContainingView/component.tsx
src/wrappers/responsiveHidingView/component.tsx
src/wrappers/responsiveTextAlignmentView/component.tsx

Fiddle: update prop names for new styled components version

---

CHANGELOG.md
package-lock.json
package.json
src/atoms/prettyText/component.tsx
src/molecules/markdown/component.tsx
src/molecules/markdown/documentation.stories.mdx

Fix: corrections for markdown

---

CHANGELOG.md
src/atoms/button/component.tsx

Fiddle: add isFullHeight to Button

---

CHANGELOG.md
src/molecules/markdown/component.tsx

Fiddle: Update Markdown to render bullets without spaces in between

---

CHANGELOG.md
src/atoms/iconButton/component.tsx

Fiddle: add isfullHeight and isFullWidth to IconButton

---

CHANGELOG.md
src/particles/image/buildTheme.ts

Fix: correction for Image opacity during lazy loading

---

src/molecules/markdown/component.tsx
src/molecules/markdown/documentation.stories.mdx

Fiddle: update markdown to render underlines as component

---

CHANGELOG.md
src/molecules/inputFrame/component.tsx
src/molecules/optionSelect/component.tsx
src/molecules/singleLineInput/component.tsx
src/particles/portal/buildTheme.ts
src/particles/portal/component.tsx

Feature: add more power to OptionSelect and Portal

---

CHANGELOG.md
src/molecules/markdown/component.tsx

Fixed: Changed Markdown to render bullets with nested children

---

src/util/themeUtil.ts

Fix: correct mergeTheme function

---

src/molecules/markdown/component.tsx
src/wrappers/colorSettingView/component.tsx

Fix: wrap markdown in span + fix colorSettingView with default

---

CHANGELOG.md
src/atoms/inputWrapper/component.tsx

Fiddle: remove tabIndex from InputWrapper

---

CHANGELOG.md
package-lock.json
package.json
src/molecules/markdown/component.tsx
src/molecules/markdownText/component.tsx

Fiddle: convert package to es-module

---

CHANGELOG.md
src/atoms/prettyText/component.tsx
src/molecules/markdown/component.tsx

Fiddle: add params to Markdown

---

src/atoms/checkbox/component.tsx

Fiddle: small correction for checkbox

---

src/atoms/button/component.tsx
src/layouts/stack/component.tsx
src/model/alignment.ts

Fix: correct child alignment for button

---

CHANGELOG.md
src/molecules/multiLineInput/component.tsx
src/particles/portal/component.tsx

Fiddle: Add isResizableVertically and isResizableHorizontally to MultiLineInput
